name: whatsapp_direct_link
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.0
  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  equatable: ^2.0.5
  fpdart: ^0.4.0
  shared_preferences: ^2.0.16
  fluttertoast: ^8.1.2
  clipboard: ^0.1.3
  url_launcher: ^6.1.8

dev_dependencies:
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter

  mockito: ^5.3.2
  flutter_lints: ^2.0.0
  value_listenable_test: ^0.0.1


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
