// Mocks generated by Mockito 5.3.2 from annotations
// in whatsapp_direct_link/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:shared_preferences/shared_preferences.dart' as _i8;
import 'package:whatsapp_direct_link/app/core/error/failure.dart' as _i5;
import 'package:whatsapp_direct_link/app/core/usercases/usercase.dart' as _i12;
import 'package:whatsapp_direct_link/app/features/whatsapp_link/data/datasources/whatsapp_link_local_datasource.dart'
    as _i7;
import 'package:whatsapp_direct_link/app/features/whatsapp_link/domain/entities/link_historic.dart'
    as _i11;
import 'package:whatsapp_direct_link/app/features/whatsapp_link/domain/entities/whatsapp_link.dart'
    as _i6;
import 'package:whatsapp_direct_link/app/features/whatsapp_link/domain/repositories/whatsapp_link_repository.dart'
    as _i2;
import 'package:whatsapp_direct_link/app/features/whatsapp_link/domain/usercases/delete_historic_all.dart'
    as _i13;
import 'package:whatsapp_direct_link/app/features/whatsapp_link/domain/usercases/delete_historic_item.dart'
    as _i14;
import 'package:whatsapp_direct_link/app/features/whatsapp_link/domain/usercases/get_historic_whatsapp_link.dart'
    as _i10;
import 'package:whatsapp_direct_link/app/features/whatsapp_link/domain/usercases/get_whatsapp_direct_link.dart'
    as _i9;
import 'package:whatsapp_direct_link/app/shared/confirmations/confirmation_dialog.dart'
    as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWhatsappLinkRepository_0 extends _i1.SmartFake
    implements _i2.WhatsappLinkRepository {
  _FakeWhatsappLinkRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WhatsappLinkRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWhatsappLinkRepository extends _i1.Mock
    implements _i2.WhatsappLinkRepository {
  MockWhatsappLinkRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, String>>? getLinkDirect(
          {required _i6.WhatsappLink? whatsappLink}) =>
      (super.noSuchMethod(Invocation.method(
        #getLinkDirect,
        [],
        {#whatsappLink: whatsappLink},
      )) as _i3.Future<_i4.Either<_i5.Failure, String>>?);
  @override
  _i3.Future<_i4.Either<_i5.Failure, bool>>? remove({required int? index}) =>
      (super.noSuchMethod(Invocation.method(
        #remove,
        [],
        {#index: index},
      )) as _i3.Future<_i4.Either<_i5.Failure, bool>>?);
}

/// A class which mocks [WhatsappLinkLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWhatsappLinkLocalDataSource extends _i1.Mock
    implements _i7.WhatsappLinkLocalDataSource {
  MockWhatsappLinkLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> save(String? url) => (super.noSuchMethod(
        Invocation.method(
          #save,
          [url],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<bool>? remove(int? index) => (super.noSuchMethod(Invocation.method(
        #remove,
        [index],
      )) as _i3.Future<bool>?);
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i8.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() => (super.noSuchMethod(
        Invocation.method(
          #getKeys,
          [],
        ),
        returnValue: <String>{},
      ) as Set<String>);
  @override
  Object? get(String? key) => (super.noSuchMethod(Invocation.method(
        #get,
        [key],
      )) as Object?);
  @override
  bool? getBool(String? key) => (super.noSuchMethod(Invocation.method(
        #getBool,
        [key],
      )) as bool?);
  @override
  int? getInt(String? key) => (super.noSuchMethod(Invocation.method(
        #getInt,
        [key],
      )) as int?);
  @override
  double? getDouble(String? key) => (super.noSuchMethod(Invocation.method(
        #getDouble,
        [key],
      )) as double?);
  @override
  String? getString(String? key) => (super.noSuchMethod(Invocation.method(
        #getString,
        [key],
      )) as String?);
  @override
  bool containsKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: false,
      ) as bool);
  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(
        #getStringList,
        [key],
      )) as List<String>?);
  @override
  _i3.Future<bool> setBool(
    String? key,
    bool? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBool,
          [
            key,
            value,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<bool> setInt(
    String? key,
    int? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setInt,
          [
            key,
            value,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<bool> setDouble(
    String? key,
    double? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDouble,
          [
            key,
            value,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<bool> setString(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setString,
          [
            key,
            value,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<bool> setStringList(
    String? key,
    List<String>? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setStringList,
          [
            key,
            value,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<bool> remove(String? key) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<bool> commit() => (super.noSuchMethod(
        Invocation.method(
          #commit,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<bool> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [GetWhatsappDirectLink].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWhatsappDirectLink extends _i1.Mock
    implements _i9.GetWhatsappDirectLink {
  MockGetWhatsappDirectLink() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.WhatsappLinkRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeWhatsappLinkRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.WhatsappLinkRepository);
  @override
  _i3.Future<_i4.Either<_i5.Failure, String>?> call(_i6.WhatsappLink? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, String>?>.value(),
      ) as _i3.Future<_i4.Either<_i5.Failure, String>?>);
}

/// A class which mocks [GetHistoricWhatsAppLink].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetHistoricWhatsAppLink extends _i1.Mock
    implements _i10.GetHistoricWhatsAppLink {
  MockGetHistoricWhatsAppLink() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.WhatsappLinkRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeWhatsappLinkRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.WhatsappLinkRepository);
  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i11.LinkHistoric>>?> call(
          _i12.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i3
            .Future<_i4.Either<_i5.Failure, List<_i11.LinkHistoric>>?>.value(),
      ) as _i3.Future<_i4.Either<_i5.Failure, List<_i11.LinkHistoric>>?>);
}

/// A class which mocks [DeleteHistoricAll].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteHistoricAll extends _i1.Mock implements _i13.DeleteHistoricAll {
  MockDeleteHistoricAll() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.WhatsappLinkRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeWhatsappLinkRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.WhatsappLinkRepository);
  @override
  _i3.Future<_i4.Either<_i5.Failure, bool?>?> call(_i12.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, bool?>?>.value(),
      ) as _i3.Future<_i4.Either<_i5.Failure, bool?>?>);
}

/// A class which mocks [DeleteHistoricItem].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteHistoricItem extends _i1.Mock
    implements _i14.DeleteHistoricItem {
  MockDeleteHistoricItem() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.WhatsappLinkRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeWhatsappLinkRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.WhatsappLinkRepository);
  @override
  _i3.Future<_i4.Either<_i5.Failure, bool?>?> call(int? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, bool?>?>.value(),
      ) as _i3.Future<_i4.Either<_i5.Failure, bool?>?>);
}

/// A class which mocks [ConfirmationDialog].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfirmationDialog extends _i1.Mock
    implements _i15.ConfirmationDialog {
  MockConfirmationDialog() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool?> show() => (super.noSuchMethod(
        Invocation.method(
          #show,
          [],
        ),
        returnValue: _i3.Future<bool?>.value(),
      ) as _i3.Future<bool?>);
}
